apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: technical-documentation-suite
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "2Gi"
        run.googleapis.com/cpu: "2"
    spec:
      containerConcurrency: 4
      containers:
      - image: gcr.io/PROJECT_ID/technical-doc-suite:latest
        ports:
        - containerPort: 8080
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: "PROJECT_ID"
        - name: STORAGE_BUCKET
          value: "doc-suite-artifacts"
        - name: BIGQUERY_DATASET
          value: "documentation_analytics"
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "1Gi" 