# Cloud Build configuration for Technical Documentation Suite
# This file enables continuous deployment from GitHub to Cloud Run

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 
      'gcr.io/$PROJECT_ID/technical-doc-suite:latest',
      '-t', 
      'gcr.io/$PROJECT_ID/technical-doc-suite:$BUILD_ID',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/technical-doc-suite:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/technical-doc-suite:$BUILD_ID']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'technical-documentation-suite',
      '--image', 'gcr.io/$PROJECT_ID/technical-doc-suite:latest',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '2Gi',
      '--cpu', '2',
      '--max-instances', '10',
      '--min-instances', '0',
      '--concurrency', '4',
      '--timeout', '900s',
      '--set-env-vars', 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID,STORAGE_BUCKET=technical-documentation-suite-artifacts,BIGQUERY_DATASET=documentation_analytics,ENVIRONMENT=production,LOG_LEVEL=INFO',
      '--set-secrets', 'GEMINI_API_KEY=gemini-api-key:latest'
    ]

# Secrets will be configured after initial deployment

# Specify the images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/technical-doc-suite:latest'
  - 'gcr.io/$PROJECT_ID/technical-doc-suite:$BUILD_ID'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Timeout for the entire build
timeout: '1200s'

# Note: Region and service name are hardcoded in the deployment step 