name: Deploy Technical Documentation Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  SERVICE_NAME: technical-documentation-suite

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio
    
    - name: Run tests
      run: |
        pytest tests/ -v

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker $REGION-docker.pkg.dev
    
    - name: Build and push Docker image
      run: |
        docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/technical-doc-suite/app:$GITHUB_SHA .
        docker push $REGION-docker.pkg.dev/$PROJECT_ID/technical-doc-suite/app:$GITHUB_SHA
        
        # Also tag as latest
        docker tag $REGION-docker.pkg.dev/$PROJECT_ID/technical-doc-suite/app:$GITHUB_SHA \
                   $REGION-docker.pkg.dev/$PROJECT_ID/technical-doc-suite/app:latest
        docker push $REGION-docker.pkg.dev/$PROJECT_ID/technical-doc-suite/app:latest
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image $REGION-docker.pkg.dev/$PROJECT_ID/technical-doc-suite/app:$GITHUB_SHA \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated \
          --memory 2Gi \
          --cpu 2 \
          --max-instances 10 \
          --set-env-vars GOOGLE_CLOUD_PROJECT=$PROJECT_ID \
          --set-env-vars STORAGE_BUCKET=$PROJECT_ID-doc-suite-artifacts \
          --set-env-vars BIGQUERY_DATASET=documentation_analytics 